### ISSUE TITLE
Make Spectre play nicer with other stylesheets

### ISSUE THREAD

**Issue by davestewart** [spectre-org/spectre-css#16]
## Background

While rebuilding the docs in VitePress, it seems that Spectre could play more nicely with other stylesheets, particularly when mixing components with content.

- spectre's component styles can be impacted by other document styles
- spectre's content styles leak into the page and impact non-related components

## Proposal

Identify offending styles and fix.

### Prose

Spectre's formatting styles may impact existing component frameworks:

![image](https://github.com/spectre-org/spectre-css/assets/132681/0947e7d5-fb2c-4b2b-b953-897134854779)

![image](https://github.com/spectre-org/spectre-css/assets/132681/961f3de0-aaa8-4684-af8e-565c819bcd7b)

Optionally prefix page native tags styles with a class, i.e.:

```scss
// variables
$prose-prefix: ".prose";

// content
$prose-prefix {
  p {
    ...
  }
  ul {
    ...
  }
}
```
```html
<div class="prose">
...
</div>
```

### Pagination

Theme bullet styles may overwrite Spectre

![image](https://github.com/spectre-org/spectre-css/assets/132681/b4461914-b897-40e2-a016-a812197ba208)

Fix: ensure disk style is `none`

### Dark mode

Problems:

- background color overrides other theme
- no alternate stylesheet for dark mode

![image](https://github.com/spectre-org/spectre-css/assets/132681/78d6ebfa-4e82-448f-9757-e78a4c3aa92a)

This could prevent Spectre styling other framework's components:

### Code

![image](https://github.com/spectre-org/spectre-css/assets/132681/1a6ebacd-4f7e-469c-ba8d-47feb959c5eb)

Current rules expect `.code` to be placed on the `pre` but that's not always possible when using tools like [Shiki](https://github.com/shikijs/shiki/blob/main/docs/themes.md#loading-theme):

Fix:

```
pre code,
.code code {
```

### Image

Images are set to display as `block`:

![image](https://github.com/spectre-org/spectre-css/assets/132681/f3e74e53-1a8b-410e-81d6-7f1e348101ee)

## Notes

See also previously commented-out section in the docs regarding prefixing:

- https://spectre-org.github.io/spectre-docs/docs/get-started/build.html#prefixing

Tasks:

- [x] get this to work
- [x] see if it solves the problem

**Comment by davestewart** [comment]
See also:

- https://github.com/spectre-org/spectre-docs/issues/1

**Comment by davestewart** [comment]
See working docs / demo at:

- https://github.com/spectre-org/spectre-docs/

**Comment by atjn** [comment]
I agree with the idea that all native tags should be gated behind a class. It seems like you want to split the native tags into different buckets and guard each bucket behind a unique css class like `prose`. I can see how that might be useful, but I think most people would just want a `spectre` class that enables all native tags in one go. We could support both types.

I also think we should support a class that can disable the spectre classes again. You can do this with the [@scope](https://developer.mozilla.org/en-US/docs/Web/CSS/@scope) rule:
```css
@scope (.spectre) to (.spectre-disable) {
  p {
    ...
  }
  ul {
    ...
  }
}
```
Unfortunately we will only be able to use this in about one year, when the next ESR of Firefox is released (presumably) with support for this.

**Comment by davestewart** [comment]
Hey Anton,

I'm actually on this now:

- https://github.com/spectre-org/spectre-css/pull/50

I have namespacing working, and I'm just working on prefixing:

```scss
// namespace, e.g. ".docs"
.label { ... } --> .docs .label { ... }

// prefix, e.g. ".s-"
.label { ... } --> .s-label { ... }
```

A few things came up this weekend which meant I only had a few random hours over the weekend :(
