### ISSUE TITLE
Formatting is undesirable with a CSS reset

### ISSUE THREAD

**Issue by davestewart** [spectre-org/spectre-css#20]
## Background

It seems that some formatting (at least paragraphs) rely on the browser's default user agent styling.

Thus, if a [CSS reset](https://meyerweb.com/eric/tools/css/reset/) is added to a project, paragraphs butt up to the elements above.

## Proposal

Either:

- add a basic reset
- or design as if a reset had been applied

**Comment by ma4nn** [comment]
Spectre currently uses a customized version of [normalize.css](https://necolas.github.io/normalize.css/): https://github.com/spectre-org/spectre-css/blob/main/src/_normalize.scss

**Comment by davestewart** [comment]
Yeah, I realised that between now and then. We can cover this in our call

**Comment by davestewart** [comment]
> Spectre currently uses a customized version of [normalize.css](https://necolas.github.io/normalize.css/): [main/src/_normalize.scss](https://github.com/spectre-org/spectre-css/blob/main/src/_normalize.scss?rgh-link-date=2023-10-04T16%3A33%3A53Z)

Raised in #46 and fixed in #47
