### ISSUE TITLE
PageSpeed warning: CSS Value Appearance Non Standard

### ISSUE THREAD

**Issue by Pasbiengrav** [spectre-org/spectre-css#21]
Great thanks to @davestewart for your efforts in bringing this back to life.
Good for Grav CMS default theme users.

According to [PageSpeed insights](https://pagespeed.web.dev/) on one of my Spectre using website, Google Chrome is planning to deprecate the "appearance" CSS property.
"Appearance" property is used inside Spectre css on buttons and forms as well as in Spectre Exp.

Not sure if this needs to be addressed.

**Comment by davestewart** [comment]
Hello, and thanks for the appreciation 🙏

Totally happy to look at that.

I need to decide in what order to tackle things, but stand by and I'll take a look

**Comment by atjn** [comment]
I don't think there is anything to fix here. The `appearance` property is fully supported and there is no plan to deprecate it. 

I unfortunately can't see what the original message was, but I would guess that it complained about the use of `-webkit-appearance`. That is technically a legacy property that should not be used, but it is still widely used to fix edge cases in many CSS frameworks, so I wouldn't be too worried about the use of it here.

**Comment by Pasbiengrav** [comment]
Thank you for feedback. 
I cannot see the same message anymore on PageSpeed.
`-webkit-appearance` was not mentioned in original message, otherwise I would have mentioned it.
I assume this issue can be closed.
